### PR TITLE
commiting Test2 to BranchX

### PR DESCRIPTION
**Pull request by VineethRajendran21**
I have completed the code. Please review and approve

### CODE REVIEW

**Comment by VineethRajendran7** [comment]
Hi Vineeth, Needs additional syso statement for validation

**Comment by VineethRajendran7** [comment]
Added extra sysout statement. kindly review and check.

**Comment by VineethRajendran21** [comment]
Hi Vineeth, your code looks good. now please go ahead to master branch

**Comment by VineethRajendran7** [comment]
I am adding test2 to master branch

**Pull request merged**
